stages:
  - deploy

variables:
  PROJECT_DIR: "/ahmadiehsan/app/personal_docs"
  PROJECT_ENV_DIR: "/ahmadiehsan/app/env_personal_docs"

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    GIT_STRATEGY: none
  script:
    - cd $PROJECT_DIR
    - git remote set-url origin $CI_REPOSITORY_URL
    - git reset --hard
    - git checkout $CI_COMMIT_BRANCH
    - git fetch -p origin $CI_COMMIT_BRANCH
    - git reset --hard origin/$CI_COMMIT_BRANCH
    - source $PROJECT_ENV_DIR/bin/activate
    - make requirements.install
    - make app.build
