site_name: Ehsan Ahmadi's Personal Docs
site_author: Ehsan Ahmadi
copyright: ©2020-2024 Ehsan Ahmadi
theme:
  name: material
  features:
    - content.code.copy  # Adds a copy button to each code block
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: Dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: Light mode
extra:
  generator: false  # Remove the `made with MkDocs` label
plugins:
  - search
  - glightbox  # Add image lightbox feature
markdown_extensions:
  - pymdownx.superfences  # Add code blocks support
  - mdx_truly_sane_lists:  # Add nested lists support
      truly_sane: false  # Allow for unlimited newlines between elements of a list
extra_css:
  - _static/styles/iransans.css
  - _static/styles/hello_algo.css
  - _static/styles/hello_algo_overrides.css
  - _static/styles/extra.css
  - _static/styles/rtl.css
extra_javascript:
  - _static/js/extra.js
