site_name: Ehsan Ahmadi's Personal Docs
site_url: https://docs.ahmadiehsan.ir
site_author: Ehsan Ahmadi
copyright: ©2020-2025 Ehsan Ahmadi
theme:
  name: material
  features:
    - content.code.copy # Add "copy button" support to each "code block"
    - navigation.tabs # Add "top menu" support
    - navigation.indexes # Add "index pages" support for sections
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: Dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: Light mode
extra:
  generator: false # Remove the "made with MkDocs" label
  social:
    - icon: fontawesome/solid/globe
      link: https://ahmadiehsan.ir
    - icon: fontawesome/brands/github
      link: https://github.com/ahmadiehsan
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ahmadi-ehsan
    - icon: fontawesome/brands/telegram
      link: https://t.me/ahmadi_ehsan
plugins:
  - search
  - awesome-nav # Add better control over "nav" with ".nav.yml" files
  - glightbox # Add "image lightbox" feature
  - toggle-sidebar: # Add "close sidebar button" feature
      theme: material
      toggle_button: navigation
  - minify: # Minify HTML, CSS, and JS files
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - _static/css_vendor/iransans.css
        - _static/css_vendor/hello_algo.css
        - _static/css/hello_algo_overrides.css
        - _static/css/mathjax_overrides.css
        - _static/css/extra.css
        - _static/css/rtl.css
      js_files:
        - _static/js/mathjax_init.js
        - _static/js_vendor/mathjax.js
        - _static/js/extra.js
markdown_extensions:
  - md_in_html # Add "Markdown in HTML tags" support
  - admonition # Add "alert" support
  - pymdownx.details # Needed for "alert" support
  - pymdownx.superfences # Add "code blocks" support
  - pymdownx.arithmatex: # Add "inline math blocks" support
      generic: true
  - mdx_truly_sane_lists: # Add "nested lists" support
      truly_sane: false # Allow for unlimited newlines between elements of a list
extra_css:
  - _static/css_vendor/iransans.css
  - _static/css_vendor/hello_algo.css
  - _static/css/hello_algo_overrides.css
  - _static/css/mathjax_overrides.css
  - _static/css/extra.css
  - _static/css/rtl.css
extra_javascript:
  - _static/js/mathjax_init.js
  - _static/js_vendor/mathjax.js
  - _static/js/extra.js
