site_name: Ehsan Ahmadi's Personal Docs
site_url: https://docs.ahmadiehsan.ir
site_author: Ehsan Ahmadi
copyright: ©2020-2024 Ehsan Ahmadi
theme:
  name: material
  features:
    - content.code.copy  # Add "copy button" to each "code block"
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: Dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: Light mode
extra:
  generator: false  # Remove the "made with MkDocs" label
  social:
    - icon: fontawesome/solid/globe
      link: https://ahmadiehsan.ir
    - icon: fontawesome/brands/github
      link: https://github.com/ahmadiehsan
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ahmadi-ehsan
    - icon: fontawesome/brands/telegram
      link: https://t.me/ahmadi_ehsan
plugins:
  - search
  - awesome-pages  # Add better control over "nav" with ".pages" files
  - glightbox  # Add "image lightbox" feature
markdown_extensions:
  - pymdownx.superfences:  # Add "code blocks" support
      custom_fences:
        - name: mermaid  # Add "diagram" support
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:  # Add "inline math blocks" support
      generic: true
  - mdx_truly_sane_lists:  # Add "nested lists" support
      truly_sane: false  # Allow for unlimited newlines between elements of a list
extra_css:
  - _static/styles/iransans.css
  - _static/styles/hello_algo.css
  - _static/styles/hello_algo_overrides.css
  - _static/styles/mathjax.css
  - _static/styles/extra.css
  - _static/styles/rtl.css
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - _static/js/mathjax.js
  - _static/js/extra.js
