nav:
  - Index: index.md
  - 📜 Languages: languages
  - 🧩 OOP: oop
  - 📢 Protocols: protocols
  - 🗃️ Storage [DB] [Cache]: storage
  - 🌀 Algorithms: algorithms
  - 🥞 Data Structures: data_structures
  - 👷 DevOps: devops
  - "*"
